[mcp_servers.msw-maker-mcp]
command = "cmd.exe"
args = ["/c", "call", "C:\\Users\\kmj69\\AppData\\Local\\Nexon\\MapleStory Worlds\\MakerMCP\\msw-maker-mcp.bat"]

[mcp_servers.msw-mcp]
url = "https://msw-mcp.nexon.com/mcp"
http_headers = { "Authorization" = "Bearer 69dbe778af97492fbb84a4ffd1645722" }
